=== KAPILNAMDEO/Week-5/src/main/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "integer" },
      "name": { "type": "string" },
      "email": { "type": "string", "format": "email" },
      "age": { "type": "integer" },
      "city": { "type": "string" }
    },
    "required": ["id", "name", "email"]
  }
}

=== KAPILNAMDEO/Week-5/src/main/resources/data.json
[
  {
    "id": 101,
    "name": "Vidhi Jain",
    "email": "vidhijain@gmail.com",
    "age": 21,
    "city": "Bhopal"
  },
  {
    "id": 102,
    "name": "Suhani Choudhary",
    "email": "choudharysuhani@gmail.com",
    "age": 21,
    "city": "Betul"
  },
  {
    "id": 103,
    "name": "Kapil Shreasth",
    "email": "kapilshreasth@gmail.com",
    "age": 20,
    "city": "india"
  }
]
